spring:
  profiles:
    active:
	-dev
	
---
spring:
  profiles: dev   #开发环境
  application:
    name: microservicecloud-config-example-dev
---	
spring:
  profiles: test   #测试环境
  application:
    name: microservicecloud-config-example-test
	